{
 "title": "Subspace-new",
 "description": "Subspace network node and farmer dashboard",
 "tags": [ "Subspace" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "farm_id", "query": { "query": "label_values(farm_id)" } },
   { "name": "label", "query": { "query": "label_values(label)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", label=~\"$label\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{label=~\"$label\"} / node_memory_MemTotal_bytes{label=~\"$label\"})) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{label=~\"$label\"} - node_memory_SwapFree_bytes{label=~\"$label\"}) / (node_memory_SwapTotal_bytes{label=~\"$label\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{label=~\"$label\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{label=~\"$label\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Node active connections",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "subspace_established_connections{}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Sync node  peers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_sync_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blocks imported (rate)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "targets": [
    {
     "expr": "rate(subspace_node_blocks[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks imported (total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "subspace_node_blocks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node P2P data rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_network_bytes_total[5m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Current P2P data rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_network_bytes_total[5m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "subspace_node_extrinsics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "subspace_node_extrinsics", "legendFormat": "__auto" }
   ]
  },
  { "title": "Farmer (plotting)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Farmer connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "subspace_farmer_subspace_established_connections{}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Sectors downloaded total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "subspace_farmer_farm_sector_downloaded_counter_Sectors_total",
     "legendFormat": "{{farm_id}}"
    }
   ]
  },
  {
   "title": "Sectors plotted total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subspace_farmer_farm_sector_plotted_counter_Sectors_total",
     "legendFormat": "{{farm_id}}"
    }
   ]
  },
  {
   "title": "Plotting $farm_id",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "repeat": "farm_id",
   "targets": [
    {
     "expr": "subspace_farmer_farm_sectors_total_Sectors{state=\"Plotted\", farm_id=\"$farm_id\"}",
     "legendFormat": "Plotted"
    },
    {
     "expr": "subspace_farmer_farm_sectors_total_Sectors{state=\"NotPlotted\", farm_id=\"$farm_id\"}",
     "legendFormat": "Not plotted"
    },
    {
     "expr": "subspace_farmer_farm_sectors_total_Sectors{state=\"Expired\", farm_id=\"$farm_id\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "subspace_farmer_farm_sectors_total_Sectors{state=\"AboutToExpire\", farm_id=\"$farm_id\"}",
     "legendFormat": "About to expire"
    }
   ]
  },
  {
   "title": "Sector download time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Sector encode time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Sector plot time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Sector write time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  { "title": "Farmer (farming)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Auditing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Proving time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Farmer (cache)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity $farm_id",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
     "repeat": "farm_id",
     "targets": [
      {
       "expr": "subspace_farmer_disk_piece_cache_capacity_total_Pieces{cache_id=\"$farm_id\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "subspace_farmer_disk_piece_cache_capacity_used_Pieces{cache_id=\"$farm_id\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "custom_metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true
  },
  {
   "title": "NODE warn in logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 56 },
   "targets": [
    { "expr": "rate(logs_node_warn_cnt[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NODE error in logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 56 },
   "targets": [
    { "expr": "rate(logs_node_error_cnt[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NODE time from restart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "node_restart_time{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FARMER warn in logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 2, "x": 8, "y": 56 },
   "targets": [
    { "expr": "rate(farmer_node_warn_cnt[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FARMER error in logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 56 },
   "targets": [
    {
     "expr": "rate(logs_farmer_error_cnt[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FARMER time from restart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    { "expr": "farmer_restart_time{}", "legendFormat": "__auto" }
   ]
  }
 ]
}